/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ThanksRouteImport } from './routes/thanks'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AdminAdminsRouteImport } from './routes/admin.admins'
import { Route as AdminChallengeRouteImport } from './routes/admin.challenge'
import { Route as AdminChallengesRouteImport } from './routes/admin.challenges'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminExamRouteImport } from './routes/admin.exam'
import { Route as AdminGroupsRouteImport } from './routes/admin.groups'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminQuestionsRouteImport } from './routes/admin.questions'
import { Route as ChallengesSlugRouteImport } from './routes/challenges.$slug'
import { Route as CohortIndexRouteImport } from './routes/cohort.index'
import { Route as CohortCohortIdRouteImport } from './routes/cohort.$cohortId'
import { Route as ExamsSlugRouteImport } from './routes/exams.$slug'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AdminApplicationsIdRouteImport } from './routes/admin.applications.$id'
import { Route as AdminExamQuestionsRouteImport } from './routes/admin.exam_.questions'
import { Route as ChallengesSlugLeaderboardRouteImport } from './routes/challenges.$slug_.leaderboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ThanksRoute = ThanksRouteImport.update({
  id: '/thanks',
  path: '/thanks',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChallengeRoute = AdminChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChallengesRoute = AdminChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExamRoute = AdminExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGroupsRoute = AdminGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AdminRoute,
} as any)
const ChallengesSlugRoute = ChallengesSlugRouteImport.update({
  id: '/challenges/$slug',
  path: '/challenges/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CohortIndexRoute = CohortIndexRouteImport.update({
  id: '/cohort/',
  path: '/cohort/',
  getParentRoute: () => rootRouteImport,
} as any)
const CohortCohortIdRoute = CohortCohortIdRouteImport.update({
  id: '/cohort/$cohortId',
  path: '/cohort/$cohortId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsSlugRoute = ExamsSlugRouteImport.update({
  id: '/exams/$slug',
  path: '/exams/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsIdRoute = AdminApplicationsIdRouteImport.update({
  id: '/applications/$id',
  path: '/applications/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExamQuestionsRoute = AdminExamQuestionsRouteImport.update({
  id: '/exam_/questions',
  path: '/exam/questions',
  getParentRoute: () => AdminRoute,
} as any)
const ChallengesSlugLeaderboardRoute =
  ChallengesSlugLeaderboardRouteImport.update({
    id: '/challenges/$slug_/leaderboard',
    path: '/challenges/$slug/leaderboard',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRoute
  '/mcp': typeof McpRoute
  '/thanks': typeof ThanksRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/challenge': typeof AdminChallengeRoute
  '/admin/challenges': typeof AdminChallengesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/exam': typeof AdminExamRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/challenges/$slug': typeof ChallengesSlugRoute
  '/cohort/$cohortId': typeof CohortCohortIdRoute
  '/exams/$slug': typeof ExamsSlugRoute
  '/cohort/': typeof CohortIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/admin/exam/questions': typeof AdminExamQuestionsRoute
  '/challenges/$slug/leaderboard': typeof ChallengesSlugLeaderboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRoute
  '/mcp': typeof McpRoute
  '/thanks': typeof ThanksRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/challenge': typeof AdminChallengeRoute
  '/admin/challenges': typeof AdminChallengesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/exam': typeof AdminExamRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/challenges/$slug': typeof ChallengesSlugRoute
  '/cohort/$cohortId': typeof CohortCohortIdRoute
  '/exams/$slug': typeof ExamsSlugRoute
  '/cohort': typeof CohortIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/admin/exam/questions': typeof AdminExamQuestionsRoute
  '/challenges/$slug/leaderboard': typeof ChallengesSlugLeaderboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRoute
  '/mcp': typeof McpRoute
  '/thanks': typeof ThanksRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/challenge': typeof AdminChallengeRoute
  '/admin/challenges': typeof AdminChallengesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/exam': typeof AdminExamRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/challenges/$slug': typeof ChallengesSlugRoute
  '/cohort/$cohortId': typeof CohortCohortIdRoute
  '/exams/$slug': typeof ExamsSlugRoute
  '/cohort/': typeof CohortIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/admin/exam_/questions': typeof AdminExamQuestionsRoute
  '/challenges/$slug_/leaderboard': typeof ChallengesSlugLeaderboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apply'
    | '/mcp'
    | '/thanks'
    | '/.well-known/oauth-protected-resource'
    | '/admin/admins'
    | '/admin/challenge'
    | '/admin/challenges'
    | '/admin/dashboard'
    | '/admin/exam'
    | '/admin/groups'
    | '/admin/login'
    | '/admin/questions'
    | '/challenges/$slug'
    | '/cohort/$cohortId'
    | '/exams/$slug'
    | '/cohort/'
    | '/.lovable/oauth/consent'
    | '/admin/applications/$id'
    | '/admin/exam/questions'
    | '/challenges/$slug/leaderboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apply'
    | '/mcp'
    | '/thanks'
    | '/.well-known/oauth-protected-resource'
    | '/admin/admins'
    | '/admin/challenge'
    | '/admin/challenges'
    | '/admin/dashboard'
    | '/admin/exam'
    | '/admin/groups'
    | '/admin/login'
    | '/admin/questions'
    | '/challenges/$slug'
    | '/cohort/$cohortId'
    | '/exams/$slug'
    | '/cohort'
    | '/.lovable/oauth/consent'
    | '/admin/applications/$id'
    | '/admin/exam/questions'
    | '/challenges/$slug/leaderboard'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apply'
    | '/mcp'
    | '/thanks'
    | '/.well-known/oauth-protected-resource'
    | '/admin/admins'
    | '/admin/challenge'
    | '/admin/challenges'
    | '/admin/dashboard'
    | '/admin/exam'
    | '/admin/groups'
    | '/admin/login'
    | '/admin/questions'
    | '/challenges/$slug'
    | '/cohort/$cohortId'
    | '/exams/$slug'
    | '/cohort/'
    | '/.lovable/oauth/consent'
    | '/admin/applications/$id'
    | '/admin/exam_/questions'
    | '/challenges/$slug_/leaderboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApplyRoute: typeof ApplyRoute
  McpRoute: typeof McpRoute
  ThanksRoute: typeof ThanksRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ChallengesSlugRoute: typeof ChallengesSlugRoute
  CohortCohortIdRoute: typeof CohortCohortIdRoute
  ExamsSlugRoute: typeof ExamsSlugRoute
  CohortIndexRoute: typeof CohortIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ChallengesSlugLeaderboardRoute: typeof ChallengesSlugLeaderboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thanks': {
      id: '/thanks'
      path: '/thanks'
      fullPath: '/thanks'
      preLoaderRoute: typeof ThanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/challenge': {
      id: '/admin/challenge'
      path: '/challenge'
      fullPath: '/admin/challenge'
      preLoaderRoute: typeof AdminChallengeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/challenges': {
      id: '/admin/challenges'
      path: '/challenges'
      fullPath: '/admin/challenges'
      preLoaderRoute: typeof AdminChallengesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exam': {
      id: '/admin/exam'
      path: '/exam'
      fullPath: '/admin/exam'
      preLoaderRoute: typeof AdminExamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/groups': {
      id: '/admin/groups'
      path: '/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AdminGroupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/challenges/$slug': {
      id: '/challenges/$slug'
      path: '/challenges/$slug'
      fullPath: '/challenges/$slug'
      preLoaderRoute: typeof ChallengesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cohort/': {
      id: '/cohort/'
      path: '/cohort'
      fullPath: '/cohort/'
      preLoaderRoute: typeof CohortIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cohort/$cohortId': {
      id: '/cohort/$cohortId'
      path: '/cohort/$cohortId'
      fullPath: '/cohort/$cohortId'
      preLoaderRoute: typeof CohortCohortIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/$slug': {
      id: '/exams/$slug'
      path: '/exams/$slug'
      fullPath: '/exams/$slug'
      preLoaderRoute: typeof ExamsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applications/$id': {
      id: '/admin/applications/$id'
      path: '/applications/$id'
      fullPath: '/admin/applications/$id'
      preLoaderRoute: typeof AdminApplicationsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exam_/questions': {
      id: '/admin/exam_/questions'
      path: '/exam/questions'
      fullPath: '/admin/exam/questions'
      preLoaderRoute: typeof AdminExamQuestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/challenges/$slug_/leaderboard': {
      id: '/challenges/$slug_/leaderboard'
      path: '/challenges/$slug/leaderboard'
      fullPath: '/challenges/$slug/leaderboard'
      preLoaderRoute: typeof ChallengesSlugLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminChallengeRoute: typeof AdminChallengeRoute
  AdminChallengesRoute: typeof AdminChallengesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminExamRoute: typeof AdminExamRoute
  AdminGroupsRoute: typeof AdminGroupsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  AdminApplicationsIdRoute: typeof AdminApplicationsIdRoute
  AdminExamQuestionsRoute: typeof AdminExamQuestionsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminsRoute: AdminAdminsRoute,
  AdminChallengeRoute: AdminChallengeRoute,
  AdminChallengesRoute: AdminChallengesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminExamRoute: AdminExamRoute,
  AdminGroupsRoute: AdminGroupsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
  AdminApplicationsIdRoute: AdminApplicationsIdRoute,
  AdminExamQuestionsRoute: AdminExamQuestionsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApplyRoute: ApplyRoute,
  McpRoute: McpRoute,
  ThanksRoute: ThanksRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ChallengesSlugRoute: ChallengesSlugRoute,
  CohortCohortIdRoute: CohortCohortIdRoute,
  ExamsSlugRoute: ExamsSlugRoute,
  CohortIndexRoute: CohortIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ChallengesSlugLeaderboardRoute: ChallengesSlugLeaderboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
